[package]
name = "md5sum-uring"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
md-5 = "0.10.0"
structopt = "0.3.25"
